---
- hosts: webserver
  become: yes
  vars:
    myjavapackforredhat: java-1.8.0-openjdk
    myapachepackforubuntu: apache2
  tasks:
  - name: i want to install java on linux server
    yum:
      name: "{{myjavapackforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: uninstall apche server on ubuntu
    apt:
      name: "{{myapachepackforubuntu}}"
      state: absent
    when: ansible_os_family=="Debian"

  - name: install apche server on ubuntu
    apt:
      name: "{{myapachepackforubuntu}}"
      update_cache: yes
      state: latest
    when: ansible_os_family=="Debian" 

  - name: stop apache server on ubuntu
    service:
      name: "{{myapachepackforubuntu}}"
      state: stopped
    when: ansible_os_family=="Debian" 
  
  - name: run apache server on ubuntu
    service:
      name: "{{myapachepackforubuntu}}"
      state: started
    when: ansible_os_family=="Debian"