---
- hosts: webserver
  become: yes
  tasks:
  - include: installapach2.yml
  - include: installgit.yml
  - include: installtree.yml
  - include: installwget.yml
  - include: createfile.yml
  - name: i want to install tree
    apt:
      name: tree
      state: present
 
  
  
  
 