---
- hosts: webserver
  become: yes
  tasks:
  - include_tasks: installapach2.yml
  - include_tasks: installgit.yml
  - include_tasks: installtree.yml
  - include_tasks: installwget.yml
  - include_tasks: createfile.yml
  - name: i want to create a file on Node
    file:
      path: /home/maha/mytestfile1
      state: touch
 
  
  
  
 