---
- hosts: webserver
  become: yes
  tasks:
#  - include_tasks: installapach2.yml
#  - include_tasks: installgit.yml
#  - include_tasks: installtree.yml
#  - include_tasks: installwget.yml
  - include_tasks: createfile.yml
  - name: i want to install tree
    apt:
      name: tree
      state: present
 
  
  
  
 