---
- hosts: webserver
  become: yes
  tasks:
  - include_tasks: /home/maha/Ansible/installapach2.yml
  - include_tasks: /home/maha/Ansible/installgit.yml
  - include_tasks: /home/maha/Ansible/installtree.yml
  - include_tasks: /home/maha/Ansible/installwget.yml
  - include_tasks: /home/maha/Ansible/createfile.yml
  - name: i want to install tree
    apt:
      name: tree
      state: present
 
  
  
  
 