---
- hosts: webserver
  become: yes
  vars:
    myjavapackforubuntu: openjdk-14-jdk
  tasks:
  - name: i want to install java on linux
    yum:
      name: "{{myjavapackforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want to install java on ubuntu
    apt:
      name: "{{myjavapackforubuntu}}"
      state: present
      update_cache: yes
    when: ansible_os_family=="Debian"