--- 
- hosts: 172.31.91.208
  become: yes
  tasks:
  - name: Install ntp on ubuntu
    apt:
      name: ntp
      state: present
    tags: ntp
  
  - name: Configure ntp
    ansible.builtin.template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
    notify:
    - restart ntpd
    tags: ntp-config

  - name: Enable and run ntp on Ubuntu server
    service:
      name: ntpd
      state: started
    tags: ntp-enable
    
