---
- hosts: 172.31.91.208
  become: yes
  tasks:
  - name: install git,wget, tree using tags
    tags: Mahender
    block:
    - name: install git
      apt:
        name: git
        state: absent
#      debug:
#        msg: "installing git"

    - name: install wget
      apt:
        name: wget
        state: absent

    - name: install tree
      apt: 
        name: tree
        state: absent
