---
- hosts: 172.31.91.208
  become: yes
  tasks:
  - name: storing results in maha registory
    command:
      cmd: hostname -f
    register: mahi

  - name: i want to display my register maha results
    debug:
      msg: "{{mahi}}"

  - name: installing git on ubuntu server
    apt:
      name: git
      state: present

  - name: installing tree on ubuntu
    apt:
      name: tree
      state: present 
    when: mahi.stderr !=""

  - name: install ansible on ubuntu when stderr contains data
    apt:
      name: ansible
      state: present
    when: mahi.stderr ==""

  - name: install wget on ubuntu by using stdout condition
    apt:
     name: wget
     state: present
    when: mahi.stdout =="Hi"