---
- hosts: webserver
  become: yes
  tasks:
  - name: i want to install httpd on linux
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name: running on httpd server on linux
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"