---
- hosts: 172.31.31.239
  become: yes
  tasks:
  - name: install websever on ubuntu ansible nodes
    apt:
      name: "{{mywebpackforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"