---
- name: creating a new tomcat group
  group:
    name: tomcat
    state: present

- name: creating tomcat user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    home:  /opt/tomcat
    state: present